load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
  name = "com_google_googletest",
  urls = ["https://github.com/google/googletest/archive/ae1b7ad4308249bfa928e65d1a33be117fc0992c.zip"],
  strip_prefix = "googletest-ae1b7ad4308249bfa928e65d1a33be117fc0992c",
)
